version: "3.9"

services:
  pgvector:
    image: pgvector/pgvector:pg16            # ARM-native Postgres 16 + pgvector
    platform: linux/arm64/v8
    container_name: pgvector-demo
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: vectordb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432"

volumes:
  pgdata:
